import Link from 'next/link';
import './globals.css'
import { Montserrat, Open_Sans} from 'next/font/google'
import Nav from './auth/Nav';
import clsx from 'clsx';


const montserrat = Montserrat({ subsets: ['latin'], variable: '---font-montserrat' });
const openSans = Open_Sans({ subsets: ['latin'], variable: '---font-open-sans' });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(montserrat.variable, openSans.className)}>
      <body className='h-screen'>
        <Nav />
        {children}
        </body>
    </html>
  )
}
